cost_center   = "cos"
entity        = "en"
app_name      = "ess"
product       = "pro"
cia           = "cia"
function      = "fun"
channel       = "chan"
description   = "des"
tracking_code = "trc"
environment   = "env"
geo_region    = "ew1"
sequence      = "01"


kms_key_arn = ""
recovery_window_in_days = "30"
is_secret_string = "true"
secret = "name"
